name: hra-tfq
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - sympy
  - pip:
      - tensorflow==2.15.0
      - tensorflow-quantum==0.7.2
      - cirq-core==1.3.0
      - cirq-google==1.3.0
      - matplotlib
      - jupyter
